// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UITestAutomation.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("LetterTemplate")]
    public partial class LetterTemplateFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "LetterTemplate.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "LetterTemplate", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
#line 4
 testRunner.Given("User log into Dispute Tracking Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 5
 testRunner.And("User should be able to see Dashboard in Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Letter Template")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public virtual void LetterTemplate()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Letter Template", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 9
 testRunner.Given("User clicks the Profile Icon on the Dashboard page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 10
 testRunner.And("User selects the Letter Template Field from the dropdown menu of Profile Icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table62 = new TechTalk.SpecFlow.Table(new string[] {
                            "UI Controls"});
                table62.AddRow(new string[] {
                            "Add"});
                table62.AddRow(new string[] {
                            "Delete"});
                table62.AddRow(new string[] {
                            "Edit"});
                table62.AddRow(new string[] {
                            "Download from Library"});
                table62.AddRow(new string[] {
                            "Copy Letter"});
                table62.AddRow(new string[] {
                            "Action"});
                table62.AddRow(new string[] {
                            "Refresh"});
                table62.AddRow(new string[] {
                            "ID"});
                table62.AddRow(new string[] {
                            "Title"});
                table62.AddRow(new string[] {
                            "Table/Module"});
                table62.AddRow(new string[] {
                            "Reference"});
                table62.AddRow(new string[] {
                            "Enter Page"});
#line 11
 testRunner.And("User validates the following UI Controls on Letter Template Page", ((string)(null)), table62, "And ");
#line hidden
#line 26
 testRunner.And("User clicks the Add Letter Template Icon on Letter Template Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table63 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field"});
                table63.AddRow(new string[] {
                            "Title"});
                table63.AddRow(new string[] {
                            "Description"});
                table63.AddRow(new string[] {
                            "Author"});
                table63.AddRow(new string[] {
                            "File name to save letter on printing"});
                table63.AddRow(new string[] {
                            "Subject line when sending letter via email"});
                table63.AddRow(new string[] {
                            "Table Name"});
                table63.AddRow(new string[] {
                            "Reference"});
                table63.AddRow(new string[] {
                            "Workflows"});
                table63.AddRow(new string[] {
                            "SQL Command Name"});
                table63.AddRow(new string[] {
                            "Is input Form?"});
                table63.AddRow(new string[] {
                            "Is Consent notice?"});
                table63.AddRow(new string[] {
                            "Use Cut-Off print date?"});
                table63.AddRow(new string[] {
                            "Eligible for E-Signature?"});
#line 27
 testRunner.And("User validates following fields on Letter info Dialog", ((string)(null)), table63, "And ");
#line hidden
                TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field"});
                table64.AddRow(new string[] {
                            "Letter Template Form"});
#line 43
 testRunner.And("User validates following fields on Template Dialog", ((string)(null)), table64, "And ");
#line hidden
                TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field"});
                table65.AddRow(new string[] {
                            "Title"});
                table65.AddRow(new string[] {
                            "Style Sheet"});
                table65.AddRow(new string[] {
                            "Delete Template"});
                table65.AddRow(new string[] {
                            "Copy Template"});
                table65.AddRow(new string[] {
                            "Save Template"});
                table65.AddRow(new string[] {
                            "Close Template"});
#line 47
 testRunner.And("User validates following fields on Style Sheet Dialog", ((string)(null)), table65, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
