// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UITestAutomation.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("WorkflowSettings")]
    public partial class WorkflowSettingsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "WorkflowSettings.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "WorkflowSettings", "A short summary of the feature", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
#line 5
 testRunner.Given("User log into Dispute Tracking Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
 testRunner.And("User should be able to see Dashboard in Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Workflow Settings")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public virtual void WorkflowSettings()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Workflow Settings", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 10
 testRunner.Given("User clicks the Profile Icon on Dashboard page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 11
 testRunner.And("User selects the Workflow Settings Field from the dropdown menu of Profile Icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table103 = new TechTalk.SpecFlow.Table(new string[] {
                            "UI Controls"});
                table103.AddRow(new string[] {
                            "Add"});
                table103.AddRow(new string[] {
                            "Edit"});
                table103.AddRow(new string[] {
                            "Delete"});
                table103.AddRow(new string[] {
                            "Download Letter"});
                table103.AddRow(new string[] {
                            "Action"});
                table103.AddRow(new string[] {
                            "ID"});
                table103.AddRow(new string[] {
                            "Workflow"});
                table103.AddRow(new string[] {
                            "Refresh"});
#line 12
 testRunner.And("User validates the following UI Controls on Workflow Settings Page", ((string)(null)), table103, "And ");
#line hidden
#line 22
 testRunner.And("User clicks the Add Workflow Setting on on Workflow Settings Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table104 = new TechTalk.SpecFlow.Table(new string[] {
                            "Controls"});
                table104.AddRow(new string[] {
                            "Settings"});
                table104.AddRow(new string[] {
                            "Event Triggers"});
                table104.AddRow(new string[] {
                            "Self-Service Verbiage"});
                table104.AddRow(new string[] {
                            "Close"});
                table104.AddRow(new string[] {
                            "Save"});
#line 23
 testRunner.And("User validates the following Controls on Edit Setting Dialog", ((string)(null)), table104, "And ");
#line hidden
                TechTalk.SpecFlow.Table table105 = new TechTalk.SpecFlow.Table(new string[] {
                            "Fields"});
                table105.AddRow(new string[] {
                            "Workflow"});
                table105.AddRow(new string[] {
                            "Publish"});
                table105.AddRow(new string[] {
                            "Allow Customer Access"});
                table105.AddRow(new string[] {
                            "Search By"});
                table105.AddRow(new string[] {
                            "Send Notifications"});
                table105.AddRow(new string[] {
                            "Distribution List"});
                table105.AddRow(new string[] {
                            "Transaction Type"});
                table105.AddRow(new string[] {
                            "Account Types Allowed"});
                table105.AddRow(new string[] {
                            "Closed Account Status"});
                table105.AddRow(new string[] {
                            "Add Transactions"});
                table105.AddRow(new string[] {
                            "Allow Manual Transactions"});
                table105.AddRow(new string[] {
                            "Allow user to copy / duplicate transactions"});
                table105.AddRow(new string[] {
                            "Copy Description to Merchant Field by Default"});
                table105.AddRow(new string[] {
                            "Merchant Copy Source Field Name"});
                table105.AddRow(new string[] {
                            "Transaction Filter Condition"});
                table105.AddRow(new string[] {
                            "Transaction Not Allowed Condition"});
                table105.AddRow(new string[] {
                            "Show Fraud / Non-Fraud Option"});
                table105.AddRow(new string[] {
                            "Disable Customer Edit"});
                table105.AddRow(new string[] {
                            "Has Questionnaire"});
                table105.AddRow(new string[] {
                            "Has Provisional Credit Calculation"});
                table105.AddRow(new string[] {
                            "Show Customer Type"});
                table105.AddRow(new string[] {
                            "Hide Comments And Resolution"});
                table105.AddRow(new string[] {
                            "Reimburse Fees"});
                table105.AddRow(new string[] {
                            "Transaction Code Filter"});
                table105.AddRow(new string[] {
                            "GL Reference"});
                table105.AddRow(new string[] {
                            "Interest Posting GL Reference"});
                table105.AddRow(new string[] {
                            "Compliance Regulation Screen"});
                table105.AddRow(new string[] {
                            "Dispute Screen Type"});
                table105.AddRow(new string[] {
                            "Email Template Reference"});
                table105.AddRow(new string[] {
                            "Confirmation Email Template Reference"});
                table105.AddRow(new string[] {
                            "Post Submission Automation Reference"});
                table105.AddRow(new string[] {
                            "Automation Reference On Submission Complete"});
                table105.AddRow(new string[] {
                            "Submission Screen Template"});
#line 30
 testRunner.And("User validates the following Fields in Settings Page on Edit Setting Dialog", ((string)(null)), table105, "And ");
#line hidden
                TechTalk.SpecFlow.Table table106 = new TechTalk.SpecFlow.Table(new string[] {
                            "Fields",
                            "Values"});
                table106.AddRow(new string[] {
                            "Workflow",
                            "Debit Card"});
                table106.AddRow(new string[] {
                            "Publish",
                            ""});
                table106.AddRow(new string[] {
                            "Allow Customer Access",
                            ""});
                table106.AddRow(new string[] {
                            "Customer Description",
                            "Casual User"});
                table106.AddRow(new string[] {
                            "Search By",
                            "Card"});
                table106.AddRow(new string[] {
                            "Send Notifications",
                            ""});
                table106.AddRow(new string[] {
                            "Distribution List",
                            "abc"});
                table106.AddRow(new string[] {
                            "Transaction Type",
                            "Default"});
                table106.AddRow(new string[] {
                            "Account Types Allowed",
                            "Default"});
                table106.AddRow(new string[] {
                            "Closed Account Status",
                            "Default"});
                table106.AddRow(new string[] {
                            "Add Transactions",
                            ""});
                table106.AddRow(new string[] {
                            "Allow Manual Transactions",
                            ""});
                table106.AddRow(new string[] {
                            "Allow user to copy / duplicate transactions",
                            ""});
                table106.AddRow(new string[] {
                            "Copy Description to Merchant Field by Default",
                            ""});
                table106.AddRow(new string[] {
                            "Merchant Copy Source Field Name",
                            "Arshi"});
                table106.AddRow(new string[] {
                            "Transaction Filter Condition",
                            "abc"});
                table106.AddRow(new string[] {
                            "Transaction Not Allowed Condition",
                            "abc"});
                table106.AddRow(new string[] {
                            "Show Fraud / Non-Fraud Option",
                            ""});
                table106.AddRow(new string[] {
                            "Verbiage for Fraud",
                            "donot"});
                table106.AddRow(new string[] {
                            "Verbiage for Non-Fraud",
                            "problem"});
                table106.AddRow(new string[] {
                            "Disable Customer Edit",
                            ""});
                table106.AddRow(new string[] {
                            "Has Questionnaire",
                            ""});
                table106.AddRow(new string[] {
                            "Has Provisional Credit Calculation",
                            ""});
                table106.AddRow(new string[] {
                            "Show Customer Type",
                            ""});
                table106.AddRow(new string[] {
                            "Hide Comments And Resolution",
                            ""});
                table106.AddRow(new string[] {
                            "Reimburse Fees",
                            ""});
                table106.AddRow(new string[] {
                            "Transaction Code Filter",
                            "123"});
                table106.AddRow(new string[] {
                            "GL Reference",
                            "Red1"});
                table106.AddRow(new string[] {
                            "Interest Posting GL Reference",
                            "Red1"});
                table106.AddRow(new string[] {
                            "Compliance Regulation Screen",
                            "None"});
                table106.AddRow(new string[] {
                            "PC Business Days",
                            ""});
                table106.AddRow(new string[] {
                            "Provisional Credit Days",
                            "4"});
                table106.AddRow(new string[] {
                            "Resolution Business Days",
                            ""});
                table106.AddRow(new string[] {
                            "Resolution Days",
                            "12"});
                table106.AddRow(new string[] {
                            "Dispute Screen Type",
                            "Default"});
                table106.AddRow(new string[] {
                            "Email Template Reference",
                            "DC"});
                table106.AddRow(new string[] {
                            "Confirmation Email Template Reference",
                            "PC"});
                table106.AddRow(new string[] {
                            "Post Submission Automation Reference",
                            "AC"});
                table106.AddRow(new string[] {
                            "Automation Reference On Submission Complete",
                            "SFFS"});
                table106.AddRow(new string[] {
                            "Submission Screen Template",
                            "Default"});
#line 65
 testRunner.And("User adds the following data to fields in Settings Page", ((string)(null)), table106, "And ");
#line hidden
                TechTalk.SpecFlow.Table table107 = new TechTalk.SpecFlow.Table(new string[] {
                            "Fields",
                            "Values"});
                table107.AddRow(new string[] {
                            "Questionnaire Template",
                            "Check Fraud"});
                table107.AddRow(new string[] {
                            "e-Consent Notice Template",
                            "Electronic Signature Disclosure"});
                table107.AddRow(new string[] {
                            "Read Only Questionnaire",
                            ""});
                table107.AddRow(new string[] {
                            "Hide Send To Customer",
                            ""});
                table107.AddRow(new string[] {
                            "Hide Customer Acknowledgement Form",
                            ""});
                table107.AddRow(new string[] {
                            "Close Screen Message",
                            ""});
#line 107
 testRunner.And("User validates the following Fields in Questionaire Dialog on Edit Setting Dialog" +
                        "", ((string)(null)), table107, "And ");
#line hidden
#line 115
 testRunner.And("User clicks the Event Triggers in Settings Page on Edit Setting Dialog", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table108 = new TechTalk.SpecFlow.Table(new string[] {
                            "UI Controls"});
                table108.AddRow(new string[] {
                            "Action"});
                table108.AddRow(new string[] {
                            "Trigger Name"});
                table108.AddRow(new string[] {
                            "Trigger Event Type"});
                table108.AddRow(new string[] {
                            "Add"});
#line 116
 testRunner.And("User validates the following Controls in Event Triggers on Edit Setting Dialog", ((string)(null)), table108, "And ");
#line hidden
#line 122
 testRunner.And("User clicks the Add Event Trigger in Event Triggers Page on on Edit Setting Dialo" +
                        "g", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table109 = new TechTalk.SpecFlow.Table(new string[] {
                            "Fields"});
                table109.AddRow(new string[] {
                            "Trigger Name"});
                table109.AddRow(new string[] {
                            "Trigger Event Type"});
                table109.AddRow(new string[] {
                            "Additional Condition (search for below)"});
                table109.AddRow(new string[] {
                            "Account Type"});
                table109.AddRow(new string[] {
                            "Automation Reference"});
                table109.AddRow(new string[] {
                            "Letter Template Reference"});
                table109.AddRow(new string[] {
                            "GL Reference"});
                table109.AddRow(new string[] {
                            "Run Automation"});
                table109.AddRow(new string[] {
                            "AutomationReference"});
                table109.AddRow(new string[] {
                            "Send Email Notification"});
                table109.AddRow(new string[] {
                            "Email Letter Template Reference"});
                table109.AddRow(new string[] {
                            "Email Distribution List"});
                table109.AddRow(new string[] {
                            "Close"});
                table109.AddRow(new string[] {
                            "Save"});
#line 123
 testRunner.And("User validates the following Fields in Add Trigger Page on Edit Setting Dialog", ((string)(null)), table109, "And ");
#line hidden
                TechTalk.SpecFlow.Table table110 = new TechTalk.SpecFlow.Table(new string[] {
                            "Fields",
                            "Values"});
                table110.AddRow(new string[] {
                            "Trigger Name",
                            "abc"});
                table110.AddRow(new string[] {
                            "Trigger Event Type",
                            "ab"});
                table110.AddRow(new string[] {
                            "Additional Condition (search for below)",
                            ""});
                table110.AddRow(new string[] {
                            "Account Type",
                            ""});
                table110.AddRow(new string[] {
                            "Account Type Restriction",
                            "Business"});
                table110.AddRow(new string[] {
                            "Automation Reference",
                            ""});
                table110.AddRow(new string[] {
                            "Automation Reference Box",
                            "T1"});
                table110.AddRow(new string[] {
                            "Letter Template Reference",
                            ""});
                table110.AddRow(new string[] {
                            "Template Reference",
                            "ref"});
                table110.AddRow(new string[] {
                            "GL Reference",
                            ""});
                table110.AddRow(new string[] {
                            "GL Reference Box",
                            "FC"});
                table110.AddRow(new string[] {
                            "Run Automation",
                            ""});
                table110.AddRow(new string[] {
                            "AutomationReference",
                            "T1"});
                table110.AddRow(new string[] {
                            "Send Email Notification",
                            ""});
                table110.AddRow(new string[] {
                            "Email Letter Template Reference",
                            "ref"});
                table110.AddRow(new string[] {
                            "Email Distribution List",
                            "abc"});
#line 139
 testRunner.And("User adds the following data to fields in Add Trigger Page on Edit Setting Dialog" +
                        "", ((string)(null)), table110, "And ");
#line hidden
#line 157
 testRunner.And("User clicks the Save Button on Add Trigger Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 158
 testRunner.And("User clicks the Self-Service Verbiage in Settings Page on Edit Setting Dialog", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table111 = new TechTalk.SpecFlow.Table(new string[] {
                            "Fileds"});
                table111.AddRow(new string[] {
                            "Self-Service Portal Submission Completion Title"});
                table111.AddRow(new string[] {
                            "Self-Service Portal Submission Completion Note"});
                table111.AddRow(new string[] {
                            "Close"});
                table111.AddRow(new string[] {
                            "Save"});
#line 159
 testRunner.And("User validates the following Fields in Self-Service Verbiage Page on Edit Setting" +
                        " Dialog", ((string)(null)), table111, "And ");
#line hidden
                TechTalk.SpecFlow.Table table112 = new TechTalk.SpecFlow.Table(new string[] {
                            "Fileds",
                            "Value"});
                table112.AddRow(new string[] {
                            "Self-Service Portal Submission Completion Title",
                            "Completion"});
                table112.AddRow(new string[] {
                            "Self-Service Portal Submission Completion Note",
                            "Completion"});
#line 165
 testRunner.And("User adds the following data to fields in Self-Service Verbiage Page", ((string)(null)), table112, "And ");
#line hidden
#line 169
 testRunner.And("User clicks the Save Button on Self-Service Verbiage Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 170
 testRunner.And("User validates the total number of Action Fields on Workflow Settings Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 171
 testRunner.And("User clicks the Dashboard Icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
